In [1]:
import pandas as pd

# 1 Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)

In [2]:
## Reading a dataset from a csv file using pandas.
df = pd.read_csv('Laliga.csv', skiprows=1, header=0)
df.tail(5)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
56,57,Xerez,1,34,38,8,10,20,38,66,-,-,-,-,-,-,-,2009-10,2009-10,20
57,58,Condal,1,22,30,7,8,15,37,57,-,-,-,-,-,-,-,1956-57,1956-57,16
58,59,Atletico Tetuan,1,19,30,7,5,18,51,85,-,-,-,-,-,-,-,1951-52,1951-52,16
59,60,Cultural Leonesa,1,14,30,5,4,21,34,65,-,-,-,-,-,-,-,1955-56,1955-56,15
60,61,Girona,1,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2017-18,2017-18,9

In [3]:
df.describe()

             Pos    Seasons  BestPosition
count  61.000000  61.000000     61.000000
mean   31.000000  24.000000      7.081967
std    17.752934  26.827225      5.276663
min     1.000000   1.000000      1.000000
25%    16.000000   4.000000      3.000000
50%    31.000000  12.000000      6.000000
75%    46.000000  38.000000     10.000000
max    61.000000  86.000000     20.000000

In [4]:
#set and replace dashes with 0 to make sure you can perform arithmetic operations on the data.
df.replace('-', 0, inplace=True)
df.tail(3)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
58,59,Atletico Tetuan,1,19,30,7,5,18,51,85,0,0,0,0,0,0,0,1951-52,1951-52,16
59,60,Cultural Leonesa,1,14,30,5,4,21,34,65,0,0,0,0,0,0,0,1955-56,1955-56,15
60,61,Girona,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2017-18,2017-18,9

In [5]:
#Check the current datatypes of frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 20 columns):
Pos              61 non-null int64
Team             61 non-null object
Seasons          61 non-null int64
Points           61 non-null object
GamesPlayed      61 non-null object
GamesWon         61 non-null object
GamesDrawn       61 non-null object
GamesLost        61 non-null object
GoalsFor         61 non-null object
GoalsAgainst     61 non-null object
Champion         61 non-null object
Runner-up        61 non-null object
Third            61 non-null object
Fourth           61 non-null object
Fifth            61 non-null object
Sixth            61 non-null object
T                61 non-null object
Debut            61 non-null object
Since/LastApp    61 non-null object
BestPosition     61 non-null int64
dtypes: int64(3), object(17)
memory usage: 9.6+ KB

In [6]:
#Change to numeric datatype from objects
df = df.apply(pd.to_numeric, errors='ignore')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 20 columns):
Pos              61 non-null int64
Team             61 non-null object
Seasons          61 non-null int64
Points           61 non-null int64
GamesPlayed      61 non-null int64
GamesWon         61 non-null int64
GamesDrawn       61 non-null int64
GamesLost        61 non-null int64
GoalsFor         61 non-null int64
GoalsAgainst     61 non-null int64
Champion         61 non-null int64
Runner-up        61 non-null int64
Third            61 non-null int64
Fourth           61 non-null int64
Fifth            61 non-null int64
Sixth            61 non-null int64
T                61 non-null int64
Debut            61 non-null object
Since/LastApp    61 non-null object
BestPosition     61 non-null int64
dtypes: int64(17), object(3)
memory usage: 9.6+ KB

In [7]:
#Check mathematical operations can be performed, before, only 3 columns could do mathematical operations
df.describe()

,Pos,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,BestPosition
count,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000,61.000000
mean,31.000000,24.000000,901.426230,796.819672,303.967213,188.934426,303.754098,1140.344262,1140.229508,1.426230,1.409836,1.409836,1.409836,1.409836,1.409836,8.475410,7.081967
std,17.752934,26.827225,1134.899121,876.282765,406.991030,201.799477,294.708594,1506.740211,1163.710766,5.472535,4.540107,3.247445,2.746980,2.505840,2.231420,18.100282,5.276663
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,16.000000,4.000000,96.000000,114.000000,34.000000,24.000000,62.000000,153.000000,221.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,31.000000,12.000000,375.000000,423.000000,123.000000,95.000000,197.000000,430.000000,632.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000
75%,46.000000,38.000000,1351.000000,1318.000000,426.000000,330.000000,563.000000,1642.000000,1951.000000,0.000000,0.000000,1.000000,2.000000,2.000000,2.000000,6.000000,10.000000
max,61.000000,86.000000,4385.000000,2762.000000,1647.000000,633.000000,1070.000000,5947.000000,3889.000000,33.000000,25.000000,16.000000,12.000000,12.000000,10.000000,83.000000,20.000000

# 2 Print all the teams which have started playing between 1930-1980. (5 points)

In [8]:
#some Debue rows are in format 1930-42, take only first year and convert to integer.
debut_parsed = df['Debut'].apply(lambda x:int(x[:4]))
teams = df.loc[(debut_parsed >= 1930) & (debut_parsed <= 1980)]['Team'].tolist()

#Note: Considered 1930 and 1980 also.
print("Teams started playing between 1930-1980 : ", str(teams)[1:-1]) #[1:-1] to remove the brackets in list
print("Total number of teams  : ", len(teams))

Teams started playing between 1930-1980 :  'Valencia', 'Sevilla', 'Zaragoza', 'Real Betis', 'Deportivo La Coruna', 'Celta Vigo', 'Valladolid', 'Sporting Gijon', 'Osasuna', 'Malaga', 'Oviedo', 'Mallorca', 'Las Palmas', 'Granada', 'Rayo Vallecano', 'Elche', 'Hercules', 'Tenerife', 'Murcia', 'Alaves', 'Levante', 'Salamanca', 'Sabadell', 'Cadiz', 'Castellon', 'Cordoba', 'Recreativo', 'Burgos CF', 'Pontevedra', 'Gimnastic', 'Alcoyano', 'Jaen', 'AD Almeria', 'Lleida', 'Condal', 'Atletico Tetuan', 'Cultural Leonesa'
Total number of teams  :  37

# 3 Print the list of teams which came Top 5 in terms of points (2.5 points)

In [9]:
df.nlargest(5, 'Points')['Team'].tolist()

['Real Madrid', 'Barcelona', 'Atletico Madrid', 'Valencia', 'Athletic Bilbao']

# 4 Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. (5 points)

Goal_diff_count = GoalsFor - GoalsAgainst

In [10]:
def Goal_diff_count():
    columns = ['Team', 'GoalDiff']
    diff_df = pd.DataFrame(columns=columns)
    for index, row in df.iterrows():
        diff = row.GoalsFor - row.GoalsAgainst
        x = pd.Series([row['Team'], diff], columns)
        diff_df = diff_df.append(x, ignore_index=True)
    diff_df = diff_df.apply(pd.to_numeric, errors='ignore')
    #maxGoalDiff
    val = diff_df.GoalDiff.abs() #abs bcoz max goal diff can happen in -ve values also
    max_goal_diff = val.max()
    t1 = str(diff_df.iloc[[val.idxmax()]]['Team'].tolist())[2:-2]#get team and format
    #minGoalDiff, considering absoulute difference
    val = diff_df.loc[diff_df.GoalDiff.abs() > 0]['GoalDiff'].abs()
    min_goal_diff = val.min()
    t2 = str(diff_df.iloc[[val.idxmin()]]['Team'].tolist())[2:-2]#get team and format
    #minGoals, GoalsFor-GoalsAgainst
    val = diff_df.GoalDiff
    goalsFor_GoalsAgainst = val.min()
    t3 = str(diff_df.iloc[[val.idxmin()]]['Team'].tolist())[2:-2]#get team and format
    print("Maximum Goal Difference: ", max_goal_diff, "Team = ", t1 )
    print("Minimum Goal Difference: ", min_goal_diff, "Team = ", t2)
    print("Goal Difference(GoalsFor - GoalsAgainst): ", goalsFor_GoalsAgainst, "Team = ", t3)

    print()#Blank
    print("Team and Goal Differences  (Note: Negative indicates GoalsAgainst > GoalsFor)")
    print(diff_df.to_string(index=False))
Goal_diff_count()

Maximum Goal Difference:  2807 Team =  Real Madrid
Minimum Goal Difference:  2 Team =  Real Sociedad
Goal Difference(GoalsFor - GoalsAgainst):  -525 Team =  Racing Santander

Team and Goal Differences  (Note: Negative indicates GoalsAgainst > GoalsFor)
Team  GoalDiff
        Real Madrid      2807
          Barcelona      2786
    Atletico Madrid      1225
           Valencia       929
    Athletic Bilbao       931
            Sevilla       307
           Espanyol      -280
      Real Sociedad        -2
           Zaragoza      -164
         Real Betis      -333
Deportivo La Coruna      -136
         Celta Vigo      -346
         Valladolid      -413
   Racing Santander      -525
     Sporting Gijon      -399
            Osasuna      -334
             Malaga      -342
             Oviedo      -309
           Mallorca      -189
         Las Palmas      -399
         Villarreal       103
            Granada      -338
     Rayo Vallecano      -328
              Elche      -272
             Getafe      -113
           Hercules      -334
           Tenerife      -125
             Murcia      -385
             Alaves      -165
            Levante      -202
          Salamanca      -159
           Sabadell      -228
              Cadiz      -269
           Logrones      -198
          Castellon      -169
           Albacete       -90
            Almeria      -122
            Cordoba      -145
         Compostela       -42
         Recreativo       -94
          Burgos CF       -94
         Pontevedra       -56
           Numancia       -98
              Eibar       -28
             Arenas       -81
        Real Burgos       -38
          Gimnastic      -114
        Extremadura       -55
             Merida       -45
           Alcoyano      -107
               Jaen       -62
         Real Union       -31
         AD Almeria       -45
             Europa       -34
             Lleida      -112
            Leganes       -19
              Xerez       -28
             Condal       -20
    Atletico Tetuan       -34
   Cultural Leonesa       -31
             Girona         0

# 5. Create a new column with name “Winning Percent” and append it to the data set (5 points)

Percentage of Winning = (GamesWon / GamesPlayed)*100

If there are any numerical error, replace it with 0%

Print the top 5 teams which has the highest Winning percentage

In [11]:
df['Winning Percent'] = ((df.GamesWon/df.GamesPlayed) * 100).fillna(value=0)
df.tail(3)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,Winning Percent
58,59,Atletico Tetuan,1,19,30,7,5,18,51,85,...,0,0,0,0,0,0,1951-52,1951-52,16,23.333333
59,60,Cultural Leonesa,1,14,30,5,4,21,34,65,...,0,0,0,0,0,0,1955-56,1955-56,15,16.666667
60,61,Girona,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2017-18,2017-18,9,0.000000

In [12]:
print("Top 5 Teams with highest winning percent")
df.nlargest(5, 'Winning Percent')['Team'].tolist()

Top 5 Teams with highest winning percent

['Real Madrid', 'Barcelona', 'Atletico Madrid', 'Valencia', 'Athletic Bilbao']

# 6. Group teams based on their “Best position” and print the sum of their points for all positions (5 points)

Eg: Best Position     Points

         1                   25000

         2                    7000

In [13]:
x = df.groupby(['BestPosition'])['Points'].sum()
print(x.reset_index().to_string(index=False))

BestPosition  Points
           1   27933
           2    6904
           3    5221
           4    6563
           5    1884
           6    2113
           7    1186
           8    1134
           9      96
          10     450
          11     445
          12     511
          14      71
          15      14
          16      81
          17     266
          19      81
          20      34